"""initial migration

Revision ID: afaf2d923ee7
Revises: 
Create Date: 2026-09-18 19:57:18.523602
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'afaf2d923ee7'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
